development:
  encoding: utf8
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>_development

test:
  encoding: utf8
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>_test

production:
  encoding: utf8
  pool: 100
  url: hanumi:password@hanumi.c7bwbo70whto.us-west-2.rds.amazonaws.com:3306/hanumi
  #url: <%= ENV['DATABASE_URL'] %>
