development:
  encoding: utf8
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>_development

test:
  encoding: utf8
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>_test

production:
  pool: 100
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  #url: hanumi:password@hanumi.c7bwbo70whto.us-west-2.rds.amazonaws.com:3306/hanumi
  #url: <%= ENV['DATABASE_URL'] %>
