# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 920cbae13253924079f0c6e7b4aa850ecf15022a5c26ea6c4368ab7a34b0527577f837dad869d90ed0069758aa3d72e37659cf1da4f3965d3e97df7d29ce736e

test:
  secret_key_base: 1929ef1a1ef0c0d21088d16e303dddceaa0bc4d6f4879de9414a2b7fd51f01b2670a10a9dbc0d784d553f47fafa644bc5b804b9ee95e92edcae0912904e58ae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 920cbae13253924079f0c6e7b4aa850ecf15022a5c26ea6c4368ab7a34b0527577f837dad869d90ed0069758aa3d72e37659cf1da4f3965d3e97df7d29ce736e
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
